version: '3'

services:
  
  traefik:
    image: traefik:1.7
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - ms_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik_letsencrypt/traefik.toml:/traefik.toml
      - ./traefik_letsencrypt/acme.json:/acme.json
    container_name: traefik

  java_spring:
    depends_on:
      - "traefik"
    build: ../backend
    ports:
      - "8020:8020"
    networks:
      - ms_network
    labels:
      - "traefik.docker.network=ms_network"
      - "traefik.frontend.rule=Host:ms.api.wasaequreshi.com"
      - "traefik.enable=true"
      - "traefik.port=8020"

  # angular-service: 
  #   depends_on:
  #     - "traefik"
  #   container_name: mn-app 
  #   build: ../frontend
  #   volumes: # Volume binding
  #     - ../frontend:/app
  #   ports: 
  #     - '8030:8030' # Port mapping
  #   networks:
  #     - ms_network
  #   labels:
  #     - "traefik.docker.network=ms_network"
  #     - "traefik.frontend.rule=Host:ms.app.wasaequreshi.com"
  #     - "traefik.enable=true"
  #     - "traefik.port=8030"

  db:
    depends_on:
      - "traefik"
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: car_rental
      MYSQL_ROOT_PASSWORD: Sup3rS3cr3tPassw0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql_home:/var/lib/mysql
    networks:
      - ms_network 
    labels:
      - "traefik.docker.network=ms_network"
      - "traefik.frontend.rule=Host:ms.db.wasaequreshi.com"
      - "traefik.enable=true"
      - "traefik.port=3306"
 
  adminer:
    build: ./adminer
    depends_on:
      - "traefik"
      - "db"
    image: adminer
    restart: always
    links:
      - db
    ports:
      - "8010:8010"
    networks:
      - ms_network
    labels:
      - "traefik.docker.network=ms_network"
      - "traefik.frontend.rule=Host:ms.adminer.wasaequreshi.com"
      - "traefik.enable=true"
      - "traefik.port=8010"

networks:
  ms_network:
    external: true

volumes:
  mysql_home: